[server]
port="8080"
[database]
host="localhost"
port="5432"
name="postgres"
[vault]
host="localhost"
port="8200"
scheme="http"
authentication="kubernetes"
mount="kubernetes"
role="order"
[vault.credential]
serviceaccount="/var/run/secrets/kubernetes.io/serviceaccount/token"
[vault.database]
mount="database"
role="order"
[vault.transit]
key="order"
mount="transit"
