[database]
host="localhost"
port="5432"
name="postgres"
mount="database"
role="order"
[vault]
host="localhost"
port="8200"
scheme="http"
authentication="token"
role="order"
credential="00000000-0000-0000-0000-000000000000"
