[database]
server="localhost:5432"
name="postgres"
role="database/creds/order"
[vault]
host="localhost"
port="8200"
scheme="http"
authentication="token"
credential="00000000-0000-0000-0000-000000000000"
