[server]
port="8080"
[database]
host="localhost"
port="5432"
name="postgres"
[vault]
host="localhost"
port="8200"
scheme="http"
authentication="token"
role="order"
#credential="000000000000000000000000"
[vault.database]
mount="database"
role="order"
[vault.transit]
key="order"
mount="transit"
