[server]
port="3000"
[database]
host="localhost"
port="5432"
name="postgres"
[vault]
host="localhost"
port="8200"
scheme="http"
authentication="token"
[vault.credential]
#token="000000000000000000000000"
[vault.database]
mount="database"
role="order"
[vault.transit]
key="order"
mount="transit"
[vault.pki]
mount="pki"
role="order"
cn="order.hashidemos.io"
