[database]
host="localhost"
port="5432"
name="postgres"
mount="database"
role="order"
[vault]
host="localhost"
port="8200"
scheme="http"
mount="kubernetes"
authentication="kubernetes"
credential="/var/run/secrets/kubernetes.io/serviceaccount/token"
role="order"
